### ISSUE TITLE
Latest is-explicit fails

### ISSUE THREAD

**Issue by jcarpenter** [BenGaumond/after-effects#10]
I'm seeing `TypeError: is is not a function` errors on a simple test scene:

`var ae = require('after-effects');`
`ae(() => alert("Hello!\nFrom node.js"));`

The solution is to downgrade is-explicit. I dropped from 1.0.6 to 1.0.1 and the test above works without error.

Flagging for @mikkoh and @mattdesl, as it I originally encountered this  #while trying to use ae-to-json.

**Comment by BenGaumond** [comment]
Thanks for pointing this out. 

I updated is-explicit to be an es6 package, and didn't increment the version correctly.

Fixed in after-effects 0.4.10

**Comment by mikkoh** [comment]
@BenGaumond great to see this module in a repo ;) I've since left Jam3 so I haven't been as active working with After Effects.
