### ISSUE TITLE
Impressive work

### ISSUE THREAD

**Issue by fabianmoronzirfas** [BenGaumond/after-effects#14]
Hi @BenGaumond. Impressive work you did there. I invited you to our Extendscript org here on GitHub. Maybe you have something to contribute. Even if not we are happy to just grow the org with people who bring scripting for Adobe application to the next level. Your invite should be visible under https://github.com/ExtendScript or should have reached you via mail.

**Comment by BenGaumond** [comment]
Well, thanks very much Fabian! I'd be happy to join.

**Comment by fabianmoronzirfas** [comment]
Great welcome.
