### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by vespakoen** [BenGaumond/after-effects#17]
Hi there! cool package!

Are you aware of CEP? It allows you to use node.js in panels =)

I made a project recently that you might be interested in: https://github.com/vespakoen/modern-extendscript

It allows console.logging from ExtendScript (will serialize / log to the chrome remote debugger)
And does LiveReloading on save.

Check it out, you might find it useful ;)

**Comment by BenGaumond** [comment]
Very cool :)
