### ISSUE TITLE
Using @ on comments fails script execution on AE (Windows)

### ISSUE THREAD

**Issue by rafadess** [BenGaumond/after-effects#42]
I'm using this library along with typescript. Thanks for this library by the way (:

But I can't use // @ts-ignore on the code that goes to AE. It looks like the @ makes the script fail on AE javascript engine.

```
// @ts-ignore
```

A workaround is to use minify = true. Doing this the error goes away.

**Comment by corluk** [comment]
please checkout for typescript  :  [https://github.com/corluk/after-effects#develop](https://github.com/corluk/after-effects#develop)

**Comment by rafadess** [comment]
Nice! Thank you.
